version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.19.2"
      FORGEVERSION: "45.0.40"
      TYPE: FORGE
      MEMORY: ""
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./docker-data/:/data/
      - ./build/libs/:/data/mods/
